apiVersion: batch/v1
kind: Job
metadata:
  name: init-db
  namespace: default
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "2" 
spec:
  template:
    metadata:
      name: init-db
      labels:
        app: init-postgresdb
    spec:
      containers:
      - name: init-db
        image: "mysql"
        command: ["/bin/bash","-c", "mysql -h mysql --user=root --password=123456 < /sql-command/users.sql"]
        volumeMounts:
        - name: sql-command
          mountPath: /sql-command
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: db_root_password
      volumes:
        - name: sql-command
          configMap:
            # Provide the name of the ConfigMap containing the files you want
            # to add to the container
            name: sql
      restartPolicy: Never
