apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-manager
  namespace: default
rules:
  # Allow get, update and delete exclusive secrets.
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["kubernetes-dashboard-key-holder", "kubernetes-dashboard-certs", "kubernetes-dashboard-csrf"]
    verbs: ["get", "update", "delete"]
    # Allow get and update config map.
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["kubernetes-dashboard-settings"]
    verbs: ["get", "update"]
    # Allow service and network to get metrics.
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods","nodes"]
    verbs: ["proxy","get","list", "watch"]
  - apiGroups: [""]
    resources: ["services/poxey"]
    resourceNames: [""]
    verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-manager
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-manager
subjects:
  - kind: ServiceAccount
    name: kubernetes-dashboard
    namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-reader
subjects:
  - kind: ServiceAccount
    name: kubernetes-accesser
    namespace: default

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: network-manager
rules:
  - apiGroups: [""] #"" indicates the core API group
    resources: ["service","nodeport", "Secrets", "namespace","Configmap"]
    verbs: ["get", "watch", "list","create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: network-manager
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: network-manager
subjects:
  - kind: ServiceAccount
    name: kubernetes-network
    namespace: default
