apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: course-ui
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: course-ui
  template:
    metadata:
      labels:
        app: course-ui
    spec:
      containers:
      - name: {{ .Values.deployment.container.name }}
        image: {{ .Values.deployment.container.image }}
        ports:
        - containerPort: {{ .Values.deployment.container.containerPort }}
