apiVersion: v1
kind: Service
metadata:
 name: {{ .Values.service.name }}
spec:
  type: NodePort
  ports:
  - protocol: {{ .Values.service.protocol }}
    nodePort: {{ .Values.service.nodePort }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: course-ui
