apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
   name: ui-course-ingress
   namespace: default
spec:
  secretName: ui-secret
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: true
  privateKey:
    algorithm: ECDSA
    size: 256
#    algorithm: RSA
#    encoding: PKCS1
#    size: 2048
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: my-course.com
  dnsNames:
  - my-course.com ###
  #uris: ### 注释了uris、ipAddresses
  #- spiffe://cluster.local/ns/sandbox/sa/example
