apiVersion: apps/v1
kind: Deployment
metadata:
  name: courseapi-deployment
  labels:
    app: courseapi
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: courseapi
  template:
    metadata:
      labels:
        app: courseapi
    spec:
      containers:
        - name: {{ .Values.deployment.container.name }}
          image: {{ .Values.deployment.container.image }}
          ports:
            - containerPort: 5000
          env:
            - name: db_root_password
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: db_root_password
            - name: db_name
              value: Users
